# linear algebra for machine learning

#### vectors and dot products

In [20]:
import numpy as np

In [21]:
## vectors and dot product
array1=np.array([1,2,3])
array2=np.array([4,5,6])
print(np.dot(array1,array2))

32


#### matrices and operations (2d)

In [22]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [23]:
c=np.array([[1,2,3],[0,1,4],[5,6,0]])
d=np.array([[10,11,12],[13,14,15],[16,17,18]])
print(c)
print(d)

[[1 2 3]
 [0 1 4]
 [5 6 0]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


#### addition and subtraction of matrix(2 elements)

In [24]:
print("a+b\n",a+b)
print("a-b\n",a-b)

a+b
 [[ 6  8]
 [10 12]]
a-b
 [[-4 -4]
 [-4 -4]]


#### addition and subtraction of matrix(3 elements)

In [25]:
print("c+d\n",c+d)
print("c-d\n",c-d)

c+d
 [[11 13 15]
 [13 15 19]
 [21 23 18]]
c-d
 [[ -9  -9  -9]
 [-13 -13 -11]
 [-11 -11 -18]]


## matrix element wise multiplication(2D)

In [26]:
print(a*b)

[[ 5 12]
 [21 32]]


In [27]:
 print(c*d)

[[ 10  22  36]
 [  0  14  60]
 [ 80 102   0]]


## dot product of 2D array

In [28]:
print(a@b)

[[19 22]
 [43 50]]


In [29]:
print(c@d)

[[ 84  90  96]
 [ 77  82  87]
 [128 139 150]]


### transpose of matrix

In [30]:
print(a.T)

[[1 3]
 [2 4]]


In [31]:
print(c.T)

[[1 0 5]
 [2 1 6]
 [3 4 0]]


### identity matrix 

In [32]:
I=np.eye(5)
print(I)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


### matrices and operations (3d)

In [33]:
x=np.array([
             [
                 [1,2],
                 [4,5]
                 
             ],
             [
                 [0,2],
                 [2,1]
                   
             ]
           ])
y=np.array([
             [
                 [2,1],
                 [0,1]
             ],
             [
                 [0,1],
                 [1,3]
                 
             ]
           ])
print(x)
print(y)

[[[1 2]
  [4 5]]

 [[0 2]
  [2 1]]]
[[[2 1]
  [0 1]]

 [[0 1]
  [1 3]]]


In [34]:
#addition of 3d matrices
print("x+y\n",x+y)

x+y
 [[[3 3]
  [4 6]]

 [[0 3]
  [3 4]]]


In [35]:
# subtraction of 3d matrices
print("x-y\n",x-y)

x-y
 [[[-1  1]
  [ 4  4]]

 [[ 0  1]
  [ 1 -2]]]


In [36]:
# matrix multiplicaton
print(x*y)

[[[2 2]
  [0 5]]

 [[0 2]
  [2 3]]]


In [37]:
# matrix dot product pf 3d matrices

print(x.shape)
print(y.shape)
print(x@y)

(2, 2, 2)
(2, 2, 2)
[[[2 3]
  [8 9]]

 [[2 6]
  [1 5]]]


In [38]:
print(x.T)
print(y.T)

[[[1 0]
  [4 2]]

 [[2 2]
  [5 1]]]
[[[2 0]
  [0 1]]

 [[1 1]
  [1 3]]]


### inverse of matrix

In [40]:
a_inv=np.linalg.inv(a)
print(a_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [41]:
b_inv=np.linalg.inv(b)
print(b_inv)

[[-4.   3. ]
 [ 3.5 -2.5]]


In [42]:
# verify a*a-1=i(identity)
print(np.round(a@a_inv))

[[1. 0.]
 [0. 1.]]


In [ ]:
# determinant of matrix
print(a)
det_a=np.linalg.det(a)
print(det_a)

In [45]:
det_x=np.linalg.det(x)
print(det_x)

[-3. -4.]


## eigen values and eigen vectors

In [48]:
eig_vals,eig_vecs=np.linalg.eig(a)
print("e value",eig_vals)

e value [-0.37228132  5.37228132]


In [47]:
print("e vector",eig_vecs)

e vector [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
